inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rubycw

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'config.ru'
    - 'db/schema.rb'

# Style

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Metrics
Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"
