name: run_rspec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-11
    timeout-minutes: 30
    services:
      db:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby 3.0.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2

      - name: Set up Bundler
        run: gem install bundler

      - name: Solve dependencies problem
        run: brew install shared-mime-info

      - name: bundle install
        run: bundle install

      - name: Test with Rspec
        run: bundle exec rspec
