name: Run Rspec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runner-job:
    runs-on: ubuntu-latest
    env:
      ENV: runner-job
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgre
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Migrate DB schema
        shell: bash
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get github.com/rubenv/sql-migrate/...
          sql-migrate up -config=config/database.yml -env=${ENV}
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

  container-job:
    runs-on: ubuntu-latest
    container:
      image: node:15.14.0
    env:
      ENV: container-job
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby 3.0.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2

      - name: Migrate DB schema
        shell: bash
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get github.com/rubenv/sql-migrate/...
          sql-migrate up -config=config/database.yml -env=${ENV}
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432

      - name: Set up Bundler
        run: gem install bundler

      - name: Bundle Install
        run: bundle install
        
      - name: Start Postgresql
        run: brew services start postgresql

      - name: Create Database
        run: bundle exec rails db:migrate:reset

      - name: Run Rspec
        run: bundle exec rspec
