name: Run Rspec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgre
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby 3.0.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2

      - name: Set up Node.js 15.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 15.14.0

      - name: Yarn Install
        run: yarn install v1.22.15

      - name: Set up Bundler
        run: gem install bundler

      - name: Bundle Install
        run: bundle install

      - name: Copy database.yml
        run: cp config/database.yml.github-actions config/database.yml
        
      - name: Start Postgresql
        run: brew services start postgresql

      - name: Create Database
        run: bundle exec rails db:migrate:reset

      - name: Run Rspec
        run: bundle exec rspec
