# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies, and  run linters
name: cinemat

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  run-lint:
    runs-on: macos-11
    timeout-minutes: 30
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby 3.0.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2

      - name: Set up Bundler
        run: gem install bundler

      - name: Solve dependencies problem
        run: brew install shared-mime-info

      - name: bundle install
        run: bundle install

      - name: Test with Rspec
        run: |
          bundle exec rspec
